### ISSUE TITLE
Paramater timeout now used in libSonar.cpp

### ISSUE THREAD

**Issue by svicknesh** [omaflak/HC-SR04-Raspberry-Pi-C-#1]
Hi,
I was taking a look at the libSonar.cpp and realised the parameter "**timeout**" was not used in `double Sonar::distance(int timeout)`. I believe it is meant to be used in this line of code `while (digitalRead(echo) == LOW && micros()-now<30000);`.

**Comment by omaraflak** [comment]
Hi,

Yes indeed! Thanks for the report!

**Comment by svicknesh** [comment]
You're welcome. Glad to assist. :D
