### ISSUE TITLE
Too high cpu usage

### ISSUE THREAD

**Issue by MetalBlueberry** [omaflak/HC-SR04-Raspberry-Pi-C-#2]
This is working well on my RaspberryPi but I get a high cpu usage just for measuring a distance.
¿Do you know how to avoid it?

I'm trying to develop something with wiringPiISR but I'm having problems when I want to connect more than one sensor at the same time.

**Comment by omaraflak** [comment]
I'm sorry I don't really know how to fix this problem. Maybe you could change the code and measure distances at separated intervals. I already wired up to 5 sensors on a Raspberry and made them work together using a pthread for each sensor, but of course the CPU usage was very high.

Maybe someone else will help so I'm not closing this issue for now.

**Comment by Michdo93** [comment]
Well, to put it simply, it comes from measuring the distance too often. This is done constantly one after the other. If you look at the Python examples, a sleep of one second is also used here. In C++ you have to use usleep instead:

```
#include <iostream>
#include <stdio.h>
#include <wiringPi.h>
#include "libSonar.h"

using namespace std;

int trigger = 1;
int echo = 0;

int main()
{
    if (wiringPiSetup() == -1)
        return -1;

    Sonar sonar;
    sonar.init(trigger, echo);

    while(1){
        cout << "Distance is " << sonar.distance(30000) << " cm." << endl;
        usleep(1000000);
    }
}
```

For me, this has reduced the CPU load from 105% to 5-7%.
