### ISSUE TITLE
Which GPIO pins to connect to Raspberry Pi?

### ISSUE THREAD

**Issue by cws4204** [omaflak/HC-SR04-Raspberry-Pi-C-#3]
I am having a issue in determining which pins to connect the HC-SR04 to my Pi. Is there a parameter option to define the pins? 

I have the sensor confirmed working with a python script on GPIO 18 & 24 and this is not a I2C device.

Thanks!

**Comment by cws4204** [comment]
Answered my own question

Wiring Pi has its own pin numbers, GPIO 18 = WiringPi Pin 1 and GPIO 24 = WiringPi Pin 5 as per https://projects.drogon.net/raspberry-pi/wiringpi/pins/

libSonarSample.cpp
~
int trigger = 1;
int echo = 5;

**Comment by omaraflak** [comment]
I'm glad you found a solution! If you're having problems for wiring in the futur this command is super helpful : `gpio readall`

It prints a table of all the pins of your Raspberry, including the gpio ones etc.
